## Multi-node configuration

## Elasticsearch configuration

cluster.name: {{cluster_name}}

cluster.initial_master_nodes:
  - {{master_node_1}}
  - {{master_node_2}}
  - {{master_node_3}}

discovery.seed_hosts:
  - {{elasticsearch_ip_node1}}
  - {{elasticsearch_ip_node2}}
  - {{elasticsearch_ip_node3}}

## Certificates creation
          
# Clients certificates
clients:
  - name: admin
    dn: CN=admin,OU=Docu,O=Khulnasoft,L=California,C=US
    admin: true
  - name: {{khulnasoft_master_name}}
    dn: CN={{khulnasoft_master_name}},OU=Docu,O=Khulnasoft,L=California,C=US
  - name: {{khulnasoft_worker_name}}
    dn: CN={{khulnasoft_worker_name}},OU=Docu,O=Khulnasoft,L=California,C=US

# Kibana-instance
- {{kibana_ip}}

# Khulnasoft-master-configuration
- {{khulnasoft_master_server_IP}}
